# Generated by Django 3.2.3 on 2021-07-06 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('valhalla', '0002_alter_producto_numeroserie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('idProv', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Número de identificación')),
                ('img', models.ImageField(null=True, upload_to='valkyrie/', verbose_name='Logo de proveedor')),
                ('nombreP', models.CharField(max_length=50, verbose_name='Nombre de proveedor')),
                ('numTf', models.IntegerField(verbose_name='Número de teléfono')),
                ('dire', models.CharField(max_length=60, verbose_name='Dirección')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('pais', models.CharField(max_length=60, verbose_name='País')),
                ('moneda', models.CharField(max_length=7, verbose_name='Moneda de pago')),
            ],
        ),
        migrations.AlterField(
            model_name='categoria',
            name='idCategoria',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Categoria'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombreCategoria',
            field=models.CharField(max_length=60, verbose_name='Nombre de categoria'),
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valhalla.categoria'),
        ),
    ]
