# Generated by Django 3.2.3 on 2021-07-06 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valhalla', '0004_alter_proveedor_moneda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='moneda',
            field=models.CharField(max_length=7, verbose_name='Moneda de pago (Pesos o dólares)'),
        ),
    ]
